config/routes.rb
Wheelsdownat::Application.routes.draw do
  
  devise_for :users

  resources :rides, only: [:index, :create, :destroy, :update]

  get "/:about" => "rides#about"

  root :to => 'rides#index'

  

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :users

  attr_accessible :difficulty, :gmaps, :latitude, :leader, :length, :longitude, :ridename, :time, :date, :state, :city

  acts_as_gmappable

	def gmaps4rails_address
	  "#{latitude}, #{longitude}"
	end

	def gmaps4rails_infowindow
    "
    <strong>#{self.ridename}</strong>
    <ul>
	  	<li><p>Length: #{self.length}miles</p></li>
	    <li><p>Date: #{self.date}</p></li>
	    <li><p>Wheelsdown At: #{self.time}</p></li>
	    <li><p>Notes: #{self.difficulty}</p></li>
		</ul>
    "
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :rides

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  respond_to :html, :xml, :js

  def index
  	@rides_gmails = Ride.all.to_gmaps4rails
  	@rides = Ride.all
  	@new_ride = Ride.new
  end

  def create
  @ride = Ride.new(params[:ride])
   if @ride.save
    @ride_id = @ride.id
   	redirect_to rides_path
   else
     flash[:error] = "Error saving the ride."
     redirect_to rides_path
    end
  end

  def destroy
    @ride = Ride.find(params[:id])
    @ride_id = @ride.id
    @ride.destroy
    respond_with(@ride_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Wheelsdown.At</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
  	<!--  Header ================================== -->
  	<header>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/rides#index">Wheelsdown.At</a>
            <div class="nav-collapse collapse">
              <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "btn btn-small btn-inverse"  %>
                <% else %>
                  <%= link_to "Sign In", new_user_session_path, class: "btn btn-small btn-inverse" %> 
                <% end %>            
              </p>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
  	</header>

    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <%= yield %>


    <footer>
    	<%= yield :scripts %>
    	<div class="footer" id="footer">
        <div class="container">
          <%= link_to "About", "ride#about" %>
          <p>Copywrite © 2013 Wheelsdown.At</p?
       </div>
      </div>
    </footer>
  </div>
</body>

</html>

app/views/rides/about.html.erb
<div class="row-fluid" id="down">
  <div class="span12">
  	<h1>About Wheelsdown.At</h1>
  </div>
</div>

app/views/rides/destroy.js.erb
$("#ride-<%= @ride_id %>").fadeOut();

app/views/rides/edit.html.erb
<h1>Rides#edit</h1>
<p>Find me in app/views/rides/edit.html.erb</p>

app/views/rides/index.html.erb
<div class="row-fluid" id="down">
  <div class="span12">
    <%= image_tag("wheelsdown_main.png") %>
    <div class="row-fluid">
      <div class="span9">
        <%= gmaps4rails(@rides_gmails) %>
        <h3>Great Rides</h3>
        <div id="ridelist"> 
          <% @rides.each do |ride| %>
            <div id="ride-<%= ride.id %>">
              <h5><%= ride.ridename %> <%= link_to "| Delete", ride_path(ride) , :method => :delete, :remote => true %> </h5> <br>
              <p>
                <%= ride.length %>miles  | 
                <%= ride.date %> | 
                <%= ride.time %> | 
                <%= ride.difficulty %>
              </p>
              <hr>
            </div>
          <% end %>
        </div>
      </div>
       <div class="span3">
        <h4>
          Click The Map To Post A Ride
        </h4>
          <div>
            <%= form_for @new_ride do |f| %>
              <%= f.hidden_field :latitude %>
              <%= f.hidden_field :longitude %>
              <%= f.label :length, "Ride Name" %>
              <%= f.text_field :ridename, placeholder: "Ring of fire climb" %> 
              <%= f.label :length, "Length" %>
              <%= f.text_field :length, placeholder:"in miles" %>
              <%= f.label :date, "Date" %>
              <%= f.text_field :date, placeholder: "9/2/2013" %>
              <%= f.label :time, "Wheelsdown" %>
              <%= f.text_field :time, placeholder: "9:00am" %>
              <%= f.label :difficulty, "Notes" %>
              <%= f.text_area :difficulty, placeholder: "Ride meets at the corner of 5th and Main near the Peet's Coffee", size: "400" %> <br>
              <div id="rideform">
                <%= f.submit "Create Ride", class: "btn btn-primary" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rides/show.html.erb
<h1>Rides#show</h1>
<p>Find me in app/views/rides/show.html.erb</p>